spring.application.name=movie-grpc-client

spring.shell.interactive.enabled=true

spring.grpc.client.default-channel.address=${MOVIE_GRPC_SERVER_URL:localhost:9090}
spring.grpc.client.default-channel.enableKeepAlive=true
spring.grpc.client.default-channel.keepAliveWithoutCalls=true
spring.grpc.client.default-channel.negotiationType=plaintext

logging.level.root=off